//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaleInfraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int Id { get; set; }
        public double Cantidad { get; set; }
        public double ValorUnitario { get; set; }
        public double ValorTotal { get; set; }
        public Nullable<int> Cliente_Id { get; set; }
        public Nullable<int> Producto_Id { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
